#!/bin/bash

NUM_PROCS=$1

K_VALUES=(25 50 100 200)
K_LENGTH=${#K_VALUES[@]}

PATH1_VALUES=(30 60 120)
PATH1_LENGTH=${#PATH1_VALUES[@]}

PATH2_VALUES=(60 120 300 600)
PATH2_LENGTH=${#PATH2_VALUES[@]}


generate_random_number () {
    random_number=`expr \`echo $RANDOM\` % $1`
}


for (( i = 0; i < $NUM_PROCS ; i++ ))
do
    generate_random_number $K_LENGTH
    K=${K_VALUES[$random_number]}

    generate_random_number $PATH1_LENGTH
    PATH1=${PATH1_VALUES[$random_number]}

    generate_random_number $PATH2_LENGTH
    PATH2=${PATH2_VALUES[$random_number]}

    python heur3.py \
        santa.nodes \
        santa.neighbors.200 \
        santa-sol/`ls santa-sol/ | sort -g | head -n 1` \
        ~/concorde/LINKERN/linkern \
        $K \
        $PATH1 \
        $PATH2 &
done


echo "jobs:" `jobs -p`

for job in `jobs -p`
do
    echo "Waiting for" $job
    wait $job
done

echo "Done"
